#spring:
#  datasource:
#    driver-class-name: org.mariadb.jdbc.Driver
#    url: jdbc:mariadb://localhost:33660/codeboard?serverTimezone=UTC
#    username: root
#    password: testdb#
spring:
  r2dbc:
    url: r2dbc:mariadb://193.168.123.2:33001
    username: root
    password: testdb#
    name: codeboard_member
  data:
    redis:
      host: 193.168.123.2
      port: 34001
#  reactive:
#    redis:
#      host: 193.168.123.2
#      port: 33001
server:
  port: 10098

