spring:
  r2dbc:
    url: r2dbc:mariadb://localhost:33660/codeboard
    username: root
    password: testdb#
    name: codeboard_member

server:
  port: 10098

codeboard:
  auth: http://localhost:10100
  member: http://localhost:10098
